version: '3'
services:
   fba-backend:
      container_name: fba-backend
      restart: unless-stopped
      build:
         context: ./api
         dockerfile: ./Dockerfile
      ports:
         - '5000:5000'
      volumes:
         - ./db/:/app/instance/
   fba-react:
      container_name: fba-react
      restart: unless-stopped
      build:
         context: ./
         dockerfile: ./Dockerfile
      ports:
         - '3000:80'
